import json
import os
import time
from datetime import datetime, timedelta
from typing import List, Dict, Any

LOG_FILE_PATH = os.path.join("data", "decision_logs.jsonl")

def _ensure_dir():
    """Ensure the data directory exists."""
    os.makedirs(os.path.dirname(LOG_FILE_PATH), exist_ok=True)

def log_agent_decision(
    agent_name: str, 
    decision_type: str, 
    inputs: Dict[str, Any], 
    outputs: Dict[str, Any], 
    reasoning: str, 
    confidence: float, 
    incident_id: str
) -> str:
    """
    Append an agent decision to the centralized JSONL log.
    
    Args:
        agent_name (str): Name of the agent making the decision.
        decision_type (str): Category of decision (e.g., 'routing', 'rag').
        inputs (dict): Snapshot of inputs provided to the agent.
        outputs (dict): Snapshot of outputs generated by the agent.
        reasoning (str): Human-readable explanation of why the decision was made.
        confidence (float): Confidence score between 0.0 and 1.0.
        incident_id (str): Associated incident ID.
        
    Returns:
        str: The generated decision ID.
    """
    _ensure_dir()
    decision_id = f"dec_{int(time.time() * 1000)}"
    timestamp = datetime.utcnow().isoformat()
    
    entry = {
        "decision_id": decision_id,
        "timestamp": timestamp,
        "incident_id": incident_id,
        "agent": agent_name,
        "type": decision_type,
        "inputs": inputs,
        "outputs": outputs,
        "reasoning": reasoning,
        "confidence": confidence
    }
    
    with open(LOG_FILE_PATH, 'a', encoding='utf-8') as f:
        f.write(json.dumps(entry) + '\n')
        
    return decision_id

def get_decisions_for_incident(incident_id: str) -> List[Dict[str, Any]]:
    """
    Read JSONL, filter by incident_id, and return sorted by timestamp.
    
    Args:
        incident_id (str): The incident ID to query.
        
    Returns:
        List[Dict]: List of decision dictionaries.
    """
    if not os.path.exists(LOG_FILE_PATH):
        return []
        
    decisions = []
    with open(LOG_FILE_PATH, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
            try:
                data = json.loads(line)
                if data.get("incident_id") == incident_id:
                    decisions.append(data)
            except json.JSONDecodeError:
                pass
                
    return sorted(decisions, key=lambda x: x.get("timestamp", ""))

def get_decision_statistics() -> Dict[str, Any]:
    """
    Calculate summary statistics across all logged decisions.
    
    Returns:
        Dict: Contains total_decisions, avg_confidence, decisions_by_agent, low_confidence_count.
    """
    if not os.path.exists(LOG_FILE_PATH):
        return {
            "total_decisions": 0,
            "avg_confidence": 0.0,
            "decisions_by_agent": {},
            "low_confidence_count": 0
        }
        
    total_decisions = 0
    total_confidence = 0.0
    decisions_by_agent = {}
    low_confidence_count = 0
    
    with open(LOG_FILE_PATH, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
            try:
                data = json.loads(line)
                total_decisions += 1
                conf = data.get("confidence", 0.0)
                total_confidence += conf
                
                agent = data.get("agent", "unknown")
                decisions_by_agent[agent] = decisions_by_agent.get(agent, 0) + 1
                
                if conf < 0.7:
                    low_confidence_count += 1
            except json.JSONDecodeError:
                pass
                
    avg_confidence = (total_confidence / total_decisions) if total_decisions > 0 else 0.0
    
    return {
        "total_decisions": total_decisions,
        "avg_confidence": avg_confidence,
        "decisions_by_agent": decisions_by_agent,
        "low_confidence_count": low_confidence_count
    }

def clear_old_decisions(days: int = 30) -> None:
    """
    Remove entries older than the specified number of days.
    
    Args:
        days (int): Threshold in days.
    """
    if not os.path.exists(LOG_FILE_PATH):
        return
        
    cutoff_date = datetime.utcnow() - timedelta(days=days)
    kept_lines = []
    
    with open(LOG_FILE_PATH, 'r', encoding='utf-8') as f:
        for line in f:
            if not line.strip():
                continue
            try:
                data = json.loads(line)
                dt_str = data.get("timestamp", "")
                if dt_str:
                    dt = datetime.fromisoformat(dt_str)
                    if dt >= cutoff_date:
                        kept_lines.append(line)
            except (json.JSONDecodeError, ValueError):
                pass
                
    with open(LOG_FILE_PATH, 'w', encoding='utf-8') as f:
        for line in kept_lines:
            f.write(line)
